### ISSUE TITLE
Uses of `inline fun` or `inline val` are not detected

### ISSUE THREAD

**Issue by joshfriend** [autonomousapps/dependency-analysis-gradle-plugin#987] opened 2023-10-06 21:04 UTC
**Plugin version**
Reproduced with 1.23 and 1.24

Gradle: 8.3
JDK: 17.0.6
AGP: 8.1.1
Kotlin: 1.9.10

**Describe the bug**
If project A defines an `inline` fun and those are the only things used in module B, DAGP reports A as unused by B. Running `fixDependencies` will remove the dependency and cause build failures.

**Comment by autonomousapps** [comment] 2023-10-07 21:08
`AndroidKotlinInlineSpec` has a regression test related to this. If I run the test, it passes, and if I modify it to run `reason`, I'll get output like this:
```
Shortest path from :lib to androidx.core:core-ktx:1.1.0 for releaseUnitTestRuntimeClasspath:
:lib
\--- androidx.core:core-ktx:1.1.0

Source: debug, main
-------------------
* Imports 1 inline member: androidx.core.content.getSystemService (implies implementation).
```
so we are still detecting imports of inline members. Do you have a reproducer?

**Comment by autonomousapps** [comment] 2023-10-24 19:31
If I'm following you, then DAGP currently has a test that fails to show an issue here?

Is your issue specifically that `A` is an AGP project and `B` is a JVM project. `A` uses an inline function provided by `B`, and `B` only has that inline function? And DAGP says that `B` is unused?

**Comment by joshfriend** [comment] 2023-10-24 20:40
Correct. It appears that it is an AGP project using an `inline fun` from a JVM kotlin project that causes the issue. I thought this may be covered by `AndroidKotlinInlineSpec` from #173, but that test uses a KTX maven artifact and the case I am seeing is with another gradle project.

**Comment by autonomousapps** [comment] 2023-10-26 05:59
Ok, thanks for the clarification. I can write a test for this case and see what's going on.

**Comment by autonomousapps** [comment] 2023-10-26 05:59
Also ftr and because I'm feeling spikey, extension functions and properties were a mistake.

**Comment by joshfriend** [comment] 2023-10-26 12:33
> extension functions and properties were a mistake.

them's fighin' words

**Comment by autonomousapps** [comment] 2023-10-30 22:52
> > extension functions and properties were a mistake.
> 
> them's fighin' words

Ok maybe just extension properties.

**Comment by autonomousapps** [comment] 2023-11-03 20:28
I tried to validate this and failed (the test passed). See https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1018#issuecomment-1793055737

**Comment by autonomousapps** [comment] 2023-11-09 08:03
Resolved with https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1028

**Closed by autonomousapps** 2023-11-09 08:03 UTC
Labels: bug, more information needed, toolchain:android, toolchain:kotlin
