### ISSUE TITLE
> Since #916, (almost) each coordinate is wrapped in an `IncludedBuildCoordinates`. This makes the _Coordinates_ type hierarchy more complex and it now is a mix between composition and inheritance. I think it is worth to take a fresh look and possibly refactor the type hierarch of _Coordinates_ and its subtypes. The subtyping has caused other sneaky issues in the past – e.g. when comparing Coordinates (#822).

### ISSUE THREAD

**Issue by Tyszek343** [autonomousapps/dependency-analysis-gradle-plugin#1000] opened 2023-10-24 00:36 UTC
> Since #916, (almost) each coordinate is wrapped in an `IncludedBuildCoordinates`. This makes the _Coordinates_ type hierarchy more complex and it now is a mix between composition and inheritance. I think it is worth to take a fresh look and possibly refactor the type hierarch of _Coordinates_ and its subtypes. The subtyping has caused other sneaky issues in the past – e.g. when comparing Coordinates (#822).
> 
> Possible ways to go:
> - No subtyping at all - instead have one `Coordinates` type with multiple (but optional) "IDs/represenations"
> - Keep hierarchy but clean it up, move all code that is now doing a type check into methods on the `Coordinates` classes
> 
> Gains of this:
> - General more stable code with less edge cases to consider (e.g. doing different things for different `Coordinates` subtypes in multiple places.)
> - Possibly reduced memory footprint by less wrapping of many coordinates objects in many places (for large builds)
> - Reduced disc usage by more compact representations in JSON
> - Easier to read (intermediate) JSON result files
> - Cleaner API for post processor tasks
> 
> 

_Originally posted by @Tyszek343 in https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/997#issuecomment-1776026916_

**Comment by autonomousapps** [comment] 2023-10-29 21:50
Closing as a duplicate of https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/997.

**Closed by autonomousapps** 2023-10-29 21:50 UTC
