### ISSUE TITLE
Please add support for TYPESAFE_PROJECT_ACCESSORS

### ISSUE THREAD

**Issue by NikolayMetchev** [autonomousapps/dependency-analysis-gradle-plugin#1233] opened 2024-08-07 10:09 UTC
**Is your feature request related to a problem? Please describe.**
Please add support for type-safe project accessors. The feature is document here:
https://docs.gradle.org/8.9/userguide/declaring_dependencies.html#sec:type-safe-project-accessors

**Describe the solution you'd like**
Right now any findings do not use the type-safe-project-accessors syntax so you can't just copy paste to fix your deps.
It would be good if typesafe accessor is enabled that the findings match the declared deps

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by autonomousapps** [comment] 2024-08-19 18:30
Duplicate of https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/844.

**Closed by autonomousapps** 2024-08-19 18:30 UTC
